apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: testapp-rollout
spec:
  replicas: 3
  selector:
    matchLabels:
      app: testapp
  strategy:
    canary:
      canaryService: testapp-service-canary
      maxSurge: 25%
      maxUnavailable: 0
      stableService: testapp-service-stable
      steps:
      - setWeight: 10
      - setCanaryScale:
          weight: 25
      - pause:
          duration: 10s
      - setCanaryScale:
          weight: 50
      - setWeight: 30
      - pause:
          duration: 10s
      - setCanaryScale:
          weight: 75
      - setWeight: 60
      - pause:
          duration: 10s
      - setCanaryScale:
          weight: 100
      - setWeight: 100
      trafficRouting:
        nginx:
          stableIngress: testapp-ingress
  template:
    metadata:
      labels:
        app: testapp
    spec:
      containers:
      - image: nxpy/k8s-flask-app:81f5f73ccaeb90486105b7ae57784b316304a5c3
        name: testapp
        platform: linux/amd64
        ports:
        - containerPort: 80
