apiVersion: v1
kind: Deployment
metadata:
  name: testapp

spec:
  replicas: 3
  selector:
    matchLabels:
      app: testapp
  template:
    metadata:
      labels:
        app: testapp
    spec:
      containers:
      - name: testapp
        image: nxpy/k8s-flask-app
        imagePullPolicy: Never
        ports:
        - containerPort: 80
        resources:
         limits:
          memory: "200Mi"



