apiVersion: v1
kind: Service
metadata:
  name: testapp-service-canary
spec:
  ports:
  - port: 80
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app: testapp

---
apiVersion: v1
kind: Service
metadata:
  name: testapp-service-stable
spec:
  ports:
  - port: 80
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app: testapp