apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: testapp-rollout
spec:
  replicas: 3
  selector:
    matchLabels:
      app: testapp
  strategy:
    canary:
      canaryService: testapp-service-canary
      maxSurge: 25%
      maxUnavailable: 0
      stableService: testapp-service-stable
      steps:
      - setWeight: 10
      - pause:
          duration: 10s
      - setWeight: 20
      - pause: 
          duration: 10s
      - setWeight: 30
      - pause:
          duration: 10s
      # Rollout to 100% after 30s
      - setWeight: 100
      trafficRouting:
        nginx:
          stableIngress: testapp-ingress
  template:
    metadata:
      labels:
        app: testapp
    spec:
      containers:
      - image: nxpy/k8s-flask-app:c1cdca18c0569949dac9e03218ebf1f6c3bd30ac
        name: testapp
        platform: linux/amd64
        ports:
        - containerPort: 80
