apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: testapp-rollout
spec:
  replicas: 3
  selector:
    matchLabels:
      app: testapp
  strategy:
    canary:
      maxSurge: 25%
      maxUnavailable: 0
      steps:
      - setWeight: 10
      - pause:
          duration: 10s
      - setWeight: 20
      - pause: {}
  template:
    metadata:
      labels:
        app: testapp
    spec:
      containers:
      - image: nxpy/k8s-flask-app:48dc987206a712e1411831d2a7b379e4a4bf7348
        name: testapp
        platform: linux/amd64
        ports:
        - containerPort: 80
